### ISSUE TITLE
Информация об объектах коллекции должна передаваться в формате XML

### ISSUE THREAD

**Issue by AlphaBeth** [dunaevai135/soa_1#1]
По факту при создании отправляется в параметрах запроса

**Comment by dunaevai135** [comment]
Согласно заданию: "Все параметры, необходимые для выполнения операции, должны передаваться в URL запроса."

**Comment by AlphaBeth** [comment]
"Информация об объектах коллекции должна передаваться в формате XML."

Подразумевается и отправка с клиента
